name = "family-hub"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = ".output/public"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "family-hub-db"
database_id = "your-database-id-here"

